export const ACTIONS = {
  SET_REASON: "SET_REASON",
  SET_PEOPLE_TAGS: "SET_PEOPLE_TAGS",
  SET_ASSUMPTIONS: "SET_ASSUMPTIONS",
  SET_DIRECT_OUTCOMES: "SET_DIRECT_OUTCOMES",
  SET_INDIRECT_OUTCOMES: "SET_INDIRECT_OUTCOMES",
  SET_ULTIMATE_IMPACT: "SET_ULTIMATE_IMPACT",
};
